# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import requests
import json

# 1. Configuración - Usamos el nombre completo del modelo estable
API_KEY = "AIzaSyDwy6hOBHVnPNCCQDXMafTbbMKOtj9lcAc"
MODELO = "gemini-1.5-flash-latest"
URL = f"https://generativelanguage.googleapis.com/v1beta/models/{MODELO}:generateContent?key={API_KEY}"

# 2. Definición del Especialista
SYSTEM_PROMPT = """
Eres un experto en Sistemas Digitales para Ingeniería de Sistemas.
Solo respondes sobre: Compuertas lógicas, Circuitos, Arduino, Binario y Hexadecimal.
Si preguntan algo ajeno, di que solo asesoras en Sistemas Digitales.
"""

def preguntar_gemini(mensaje_usuario):
    # La estructura del JSON debe ser exacta para evitar el error 400/404
    payload = {
        "contents": [{
            "parts": [{"text": f"{SYSTEM_PROMPT}\n\nPregunta: {mensaje_usuario}"}]
        }]
    }

    headers = {'Content-Type': 'application/json'}

    try:
        response = requests.post(URL, headers=headers, data=json.dumps(payload))
        res_json = response.json()

        if response.status_code == 200:
            return res_json['candidates'][0]['content']['parts'][0]['text']
        else:
            return f"❌ Error {response.status_code}: {res_json.get('error', {}).get('message', 'Error desconocido')}"
    except Exception as e:
        return f"❌ Error de conexión: {str(e)}"

# 3. Interfaz
print("🤖 Chatbot Sistemas Digitales (Versión Final v1)")
print("Escribe 'salir' para terminar.\n")

while True:
    user_input = input("Tú: ")
    if user_input.lower() in ["salir", "exit", "chau"]:
        break

    respuesta = preguntar_gemini(user_input)
    print(f"\n🤖 Bot: {respuesta}\n")